### PR TITLE
Add Python3 support

### PR DESCRIPTION
**Pull request by Lee-W**
* Add support for python3
    * Replace `print "..."` with `print("...")`
* Add requirements.txt to indicate dependency needed (i.e. pygame)
* Ignore `.DS_STORE`, "*.pyc" and other python tmp files.
* Fix blank line and import style (following pep8)

### CODE REVIEW

**Comment by Ping-Lin** [comment]
Is there any reason why d349257 commit need to add so much unused files?
or just autogen ww

**Comment by Lee-W** [comment]
I add only one file (i.e. `.gitignore`) on commit `d349257`.
The files in `.gitignore` are files that should be ignored by git when writing python.
You can take look at [gitignore.io](https://www.gitignore.io) which provides `.gitignore` templates for various languages.

**Comment by Ping-Lin** [comment]
I meant files that you list in .gitignore.
Thanks for your information of gitignore.io.

**Comment by Lee-W** [comment]
autogen xd
They are files that possibly generated and recommended to be ignored by a python project.

**Pull request merged**
